In [1]:
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"


from IPython.display import Audio
import nltk  # we'll use this to split into sentences
import numpy as np

from bark.generation import (
    generate_text_semantic,
    preload_models,
)
from bark.api import semantic_to_waveform
from bark import generate_audio, SAMPLE_RATE

c:\Users\salos\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
preload_models()

c:\Users\salos\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")


In [11]:
script = """
Hey, have you heard about this new text-to-audio model called "Bark"? 
Apparently, it's the most realistic and natural-sounding text-to-audio model 
out there right now. People are saying it sounds just like a real person speaking. 
""".replace("\n", " ").strip()

In [12]:
sentences = nltk.sent_tokenize(script)

In [13]:
sentences

['Hey, have you heard about this new text-to-audio model called "Bark"?',
 "Apparently, it's the most realistic and natural-sounding text-to-audio model  out there right now.",
 'People are saying it sounds just like a real person speaking.']

In [19]:
SPEAKER = "v2/en_speaker_6"
silence = np.zeros(int(0.25 * SAMPLE_RATE))  # quarter second of silence

pieces = []
for sentence in sentences:
    audio_array = generate_audio(sentence, history_prompt=SPEAKER)
    pieces += [audio_array, silence.copy()]
    

100%|██████████| 18/18 [00:18<00:00,  1.01s/it]


ValueError: operands could not be broadcast together with shapes (6000,) (165760,) 

In [15]:
pieces

[array([ 1.7409438e-03,  1.0463607e-03,  1.2229092e-03, ...,
        -7.4264157e-05, -8.9080684e-05, -9.8575139e-05], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0.00139954, 0.0007363 , 0.00093676, ..., 0.00033091, 0.00033952,
        0.00034896], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([6.2614685e-04, 6.8628346e-05, 2.3432377e-04, ..., 1.9646907e-04,
        1.9011041e-04, 1.8223491e-04], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.])]

In [16]:
Audio(np.concatenate(pieces), rate=SAMPLE_RATE)